name: tricrypt_app
description: "TriCrypt - Biometric-authenticated data concealment app (image steganography + AES-256)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.17.2
  flutter_secure_storage: ^11.2.0
  local_auth: ^3.0.2
  image_picker: ^1.2.3
  sqflite: ^2.4.4
  path: ^1.9.1
  path_provider: ^2.1.6
  image_gallery_saver: ^2.0.3
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.4.2
  permission_handler: ^13.0.2
  connectivity_plus: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: MonospaceDisplay
      fonts:
        - asset: assets/fonts/MonospaceFont.ttf
